import {CharacterCreator} from "./creator.js?v=2";
import {Player} from "./player.js?v=2";
import {bindControls} from "./controls.js?v=2";
import {initMenus} from "./menus.js?v=2";
const canvas=document.getElementById("game"),ctx=canvas.getContext("2d",{alpha:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";
const GROUND_RATIO=.755,hpFill=document.getElementById("hp-fill"),staminaFill=document.getElementById("stamina-fill"),stateLabel=document.getElementById("state-label"),buildLabel=document.getElementById("build-label"),loadingFill=document.getElementById("loading-fill"),loadingBuild=document.getElementById("loading-build");
let player=null,buildConfig=null,controlsBound=false,last=performance.now();
function resize(){const ratio=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio);canvas.style.width=w+"px";canvas.style.height=h+"px";ctx.setTransform(ratio,0,0,ratio,0,0);if(player){player.groundY=h*GROUND_RATIO;if(player.onGround)player.y=player.groundY;player.x=Math.max(45,Math.min(w-45,player.x))}}
addEventListener("resize",resize,{passive:true});resize();
function enterWorld(config){buildConfig=config;document.querySelectorAll(".flow-screen").forEach(s=>s.classList.remove("active"));document.getElementById("game-shell").classList.add("active");player=new Player(innerWidth*.36,innerHeight*GROUND_RATIO);if(!controlsBound){bindControls(player);controlsBound=true}buildLabel.textContent=`${config.races.join(" / ")} · ${config.className}`;resize();last=performance.now()}
function beginGame(config){buildConfig=config;document.querySelectorAll(".flow-screen").forEach(s=>s.classList.remove("active"));const loading=document.getElementById("loading-screen");loading.classList.add("active");loadingBuild.textContent=`${config.races.join(" / ")} · ${config.className}`;loadingFill.style.width="0%";const steps=[14,36,58,80,100];let i=0;const tick=()=>{loadingFill.style.width=steps[i]+"%";i++;if(i<steps.length)setTimeout(tick,140);else setTimeout(()=>enterWorld(config),220)};setTimeout(tick,80)}
new CharacterCreator(beginGame);initMenus(()=>buildConfig);
["ability1-btn","ability2-btn","ability3-btn"].forEach((id,i)=>document.getElementById(id).onclick=()=>{const toast=document.getElementById("toast"),labels=["Radiant Burst","Aegis of Heaven","Falling Star"];toast.textContent=labels[i]+" — ability ready";toast.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>toast.classList.remove("show"),850)});
function frame(now){const dt=Math.min(.033,(now-last)/1000||.016);last=now;ctx.clearRect(0,0,innerWidth,innerHeight);if(player){if(!document.getElementById("rpgMenu").classList.contains("open"))player.update(dt);player.draw(ctx);hpFill.style.width=`${player.hp/player.maxHp*100}%`;staminaFill.style.width=`${player.stamina/player.maxStamina*100}%`;stateLabel.textContent=player.state.toUpperCase()}requestAnimationFrame(frame)}requestAnimationFrame(frame);
